name : Fitex Bikes
email : info@fitexbikes.com
permalink: pretty

collections:
  posts:
    output: true
    permalink: /blog/:title
  brands:
    output: false
  bikes:
    output: false

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          scss
  style:            :compressed